import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "quiz_over": "Quiz time is over",
          "lesson": "Lesson",
          "students_review": "Student Reviews",
          "reviews": "All Reviews",
          "notifications": "Notifications",
          "quiz_title": "Prepare yourself in online world",
          "quiz_body":
              "In our daily life, there is a use of internet almost in every work.Playing games and download, reading books, joining class, homework, buying and selling goods and foods, communication etc. almost every sector can be done with the help of internet. it makes life easier but little imbalanced use of it can be risky.",
          "quiz_button": "Assess yourself",
          "event_details": "Event Details",
          "event_date": "Event Date",
          "course": "Course",
          "video_gallery": "Video Gallery",
          "digital_literacy": "Digital Literacy",
          "solution": "Solution",
          "free_online_course": "• Complete free online course",
          "join_dlc": "Join DLC",
          "digital_jonogusti":
              "Join Digital Literacy Center to build a responsible digital society.",
          "sobar_jonno_internet": "",
          "sotto_mittha_jachai": "Fact check first,",
          'internet_share': "internet sharing later.",
          'know_more': 'Know more',
          "appName": "Digital Literacy",
          "dlcQuiz": "Digital Literacy Quiz",
          "dlcQuizDescription1": "Yours About the Internet",
          "dlcQuizDescription2": "Check knowledge",
          "joinQuiz": "Take the quiz",
          "seeMore": "See more",
          "dlcRelatedCourse": "Digital Literacy Courses",
          "dlcRelatedEvent": "Digital Literacy Events",
          "contentCreateDescription":
          "National Content Creators Conference Registration",
          "upcomingEvent": "Up coming event",
          "trending": "Trending",
          "dl": "Digital Literacy",
          "aboutDl": "Know about \n Digital Literacy",
          "photoGallery": "Photo Gallery",
          "courseDetails": "Course Details",
          "nav_home": "Home",
          "nav_quiz": "Quiz",
          "nav_course": "Courses",
          "nav_event": "Events",
          "nav_more": "More",
          "dlcNews": "Digital Literacy News",
          "hour": "Hour",
          "minute": "Minute",
          "videoCount": "Videos",
          "lessonCount": "Lesson",
          "startThisCourse": "Start now",
          "category": "Category",
          "duration": "Duration",
          "ti": "",
          "video": "Videos",
          "lecture": "Lecture",
          "level": "Level",
          "free": "Free",
          "curriculum": "Curriculum",
          "faq": "FAQ",
          "details": "Details",
          "what_you_will_learn": "What you will learn",
          "section": "Section",
          "start_course": "Start Course",
          "all_videos": "All Videos",
          "quiz": "Quiz",
          "quiz_start": "Quiz Start",
          "quiz_end": "Quiz End",
          "question": "Question",
          "leader_board": "Leaderboard",
          "score": "Score",
          'rules': "Rules",
          'about_quiz': "About Quiz",
          'conditions': 'Condition',
          'play_quiz': 'Play Quiz',
          "login": "Login",
          "account": "Account",
          "dashboard": "Dashboard",
          "certificate": "Certificate",
          "logout": "Logout",
          "settings": "Settings",
          "language": "Language",
          "others": "Others",
          "privacy_policy": "Privacy Policy",
          "terms_and_condition": "Terms & Condition",
          "app_version": "App Version",
          "enter_your_email": "Enter Your Email",
          "enter_your_password": "Enter Your Password",
          "no_account": "If you don't have an account?",
          "create_account": "Create account",
          "user_login": "User Login",
          "password_validation": "Password must be at least 8 characters long",
          "quiz_ready": 'Are you ready to play the quiz?',
          "quiz_description":
              'The countdown starts as soon as you start playing the quiz and the countdown doesnt stop even if you want to quit midway.',
          "quiz_close": "Close",
          "language_settings": "Language Settings",
          "select_language": "Select Language",
          "time": "Time",

          "join_event": 'Join Event',
          "about_event": "About Event",
          "location": "Location",

          "mobile_number": 'Mobile Number',
          "name": "Name",
          "write_your_name": "Enter Your Name",
          "father_name": 'Father Name',
          "write_father_name": 'Enter your father name',
          "mother_name": 'Mother Name',
          "write_mother_name": 'Enter your mother name',
          "select_age": "Select Age",
          "select": 'Select',
          "select_occupation": "Select Occupaiton",
          "work_place": 'Workplace',
          "write_your_work_place": 'Enter your workplace',
          "select_category": "Select Category",
          "gender_select": "Select Gender",
          "select_division": "Select Division",
          "select_district": "Select District",
          "select_upazila": "Select Upazila",
          "select_school": "Select School",
          "facebook": 'Facebook',
          "facebook_profile_link": 'Facebook Profile Link',
          "linkedin": "Linkedin",
          "linkedin_profile_link": 'Linkedin Profile Link',
          "dlc_interest": "Are you interested in doing/taking regular courses in DLC?",
          "dlc_internet": "Have you had any negative experiences on the Internet?",
          "update": 'Update',

          "registration_title": "User registration form",
          "enter_your_full_name": "Enter your full name",
          "email_not_valid": 'Email is not valid',
          "enter_your_phone_number": "Enter your mobile number",
          "select_gender": "Choose your gender",
          "enter_password": "Enter your password",
          "password_need": 'Password is required',
          "reenter_password": "Type the password again",
          "confirm_password_not_match": 'Confirm password did not match',

          "profile_update": "Profile Update",
          "write_your_phone_number": "Enter your phone number",
          "school_name": "School Name",
          "campaigns": "Campaigns",

          "are_you_sure": "Are you sure ?",
          "cancel": "Cancel",
          "delete_account": "Delete Account",
          "delete": "Delete",


          "total_school": "School Connected",
          "total_student": "Students Connected",
          "total_parents": "Parents Connected",
          "total_youths": "Youth Connected",
          "total_certificate": "Internet Pass",
          "video_library": "Video Library"
        },
        'bn_BD': {
          "course": "কোর্স",
          "video_gallery": "ভিডিও গ্যালারী",
          "digital_literacy": "ডিজিটাল লিটারেসি",
          "solution": "সল্যুশন",
          "sotto_mittha_jachai": "সত্য মিথ্যা যাচাই আগে",
          'internet_share': "ইন্টারনেটে শেয়ার পরে।",
          "free_online_course": "• সম্পূর্ণ ফ্রি অনলাইন কোর্স",
          "digital_jonogusti": "দায়িত্বশীল ডিজিটাল সমাজব্যবস্থা গড়ে তুলতে ডিজিটাল লিটারেসি সেন্টারের সাথে যুক্ত হোন।",
          "sobar_jonno_internet": "ডিজিটাল লিটারেসি সেন্টারের সাথে যুক্ত হোন।",
          "join_dlc": "যোগদিন",
          'know_more': 'আরও জানুন',
          "appName": "ডিজিটাল লিটারেসি",
          "dlcQuiz": "ডিজিটাল লিটারেসি কুইজ",
          "dlcQuizDescription1": "ইন্টারনেট সম্পর্কে আপনার",
          "dlcQuizDescription2": "জ্ঞান যাচাই করুন",
          "joinQuiz": "কুইজে অংশ নিন",
          "seeMore": "আরও দেখুন",
          "dlcRelatedCourse": "ডিজিটাল লিটারেসি কোর্স",
          "dlcRelatedEvent": "ডিজিটাল লিটারেসি ইভেন্ট",
          "contentCreateDescription":
              "জাতীয় কনটেন্ট ক্রিয়েটার কনফারেন্স নিবন্ধন",
          "upcomingEvent": "আপকামিং ইভেন্ট",
          "trending": "ট্রেন্ডিং",
          "dl": "ডিজিটাল লিটারেসি",
          "aboutDl": "ডিজিটাল লিটারেসি \n সম্পর্কে জানুন",
          "photoGallery": "ফটো গ্যালারী",
          "courseDetails": "কোর্সের বর্ণনা",
          "nav_home": "হোম",
          "nav_quiz": "কুইজ",
          "nav_course": "কোর্স",
          "nav_event": "ইভেন্ট",
          "nav_more": "আরও",
          "dlcNews": "ডিজিটাল লিটারেসি খবর",
          "hour": "ঘণ্টা",
          "minute": "মিনিট",
          "videoCount": "টি ভিডিও",
          "lessonCount": "টি লেসন",
          "startThisCourse": "কোর্সটি শুরু করুন",
          "category": "ক্যাটেগরি",
          "duration": "সময়",
          "ti": "টি",
          "video": "ভিডিও",
          "lecture": "লেখচার",
          "level": "লেভেল",
          "free": "ফ্রি",
          "curriculum": "কারিকুলাম",
          "faq": "এফএকিউ",
          "details": "বর্ণনা",
          "what_you_will_learn": "আপনি যা শিখবেন",
          "section": "সেকশান",
          "start_course": "কোর্সটি করুন",
          "all_videos": "ভিডিও সমূহ",
          "quiz": "কুইজ",
          "quiz_start": "কুইজ শুরু",
          "quiz_end": "কুইজ শেষ",
          "question": "প্রশ্ন",
          "leader_board": "লিডারবোর্ড",
          "score": "স্কোর",
          "rules": "নিয়মাবলি",
          "about_quiz": "কুইজ সম্পর্কে",
          "conditions": "শর্তসমূহ",
          'play_quiz': "কুইজ খেলুন",
          "login": "লগইন করুন",
          "account": "একাউন্ট",
          "dashboard": "ড্যাশবোর্ড",
          "certificate": "সার্টিফিকেট",
          "logout": "লগআউট",
          "settings": "সেটিংস",
          "language": "ভাষা",
          "others": "অন্যান্য",
          "privacy_policy": "প্রাইভেসী পলিসি",
          "terms_and_condition": "টার্মস & কন্ডিশনস",
          "app_version": "অ্যাপ ভার্সন",
          "event_date": "ইভেন্ট তারিখ",
          "event_details": "ইভেন্টের বিস্তারিত দেখুন",
          "quiz_title": "অনলাইন দুনিয়ায় নিজেকে প্রস্তুত করুন",
          "quiz_body":
              "দৈনন্দিন জীবনে প্রায় প্রতিটি কাজেই ইন্টারনেটের ব্যবহার রয়েছে। ইন্টারনেটের ব্যবহার জীবনকে সহজতর করেছে ঠিকই, তবে স্বাভাবিক জীবনযাত্রার সাথে এর সামঞ্জস্যতা ঠিক না থাকলে বিভিন্ন ঝুঁকির সম্মুখীন হতে হয়।",
          "quiz_button": "নিজেকে যাচাই করুন",
          "notifications": 'নোটিফিকেশন সমূহ',
          "enter_your_email": "আপনার ইমেইল দিন",
          "enter_your_password": "আপনার পাসওয়ার্ড দিন",
          "no_account": "আপনার অ্যাকাউন্ট না থাকলে?",
          "create_account": "অ্যাকাউন্ট তৈরি করুন",
          "user_login": "ব্যবহারকারী লগইন",
          "password_validation": 'পাসওয়ার্ড অবশ্যই কমপক্ষে 8 অক্ষর হতে হবে',
          "quiz_ready": 'আপনি কি কুইজ খেলার জন্য প্রস্তুত?',
          "quiz_description":
              'আপনি কুইজ খেলা শুরু করা মাত্র সময় গননা শুরু হবে এবং মাঝমাঝি বাদ দিতে চাইলেও গননা থামবে না।',
          "quiz_close": "বন্ধ করুন",
          "language_settings": "ভাষা সেটিংস",
          "select_language": "ভাষা নির্বাচন করুন",
          "students_review": "শিক্ষার্থীদের রিভিউ",
          "reviews": "রিভিউ সমূহ",
          "lesson": "লেসন",
          "quiz_over": "কুইজ এর সময় শেষ",
          "time": "সময়",
          "join_event": 'ইভেন্টে যোগ দিন',
          "about_event": "ইভেন্ট সম্বন্ধে",
          "location": "লোকেশন",

          "mobile_number": 'মোবাইল নম্বর',
          "name": "নাম",
          "write_your_name": 'আপনার নাম লিখুন',
          "father_name": 'পিতার নাম',
          "write_father_name": 'আপনার পিতার নাম লিখুন',
          "mother_name": 'মাতার নাম',
          "write_mother_name": 'মাতার নাম লিখুন',
          "select_age": "বয়স নির্বাচন করুন",
          "select": 'নির্বাচন করুন',
          "select_occupation": "পেশা নির্বাচন করুন",
          "work_place": 'প্রতিষ্ঠান/কর্মস্থল',
          "write_your_work_place": 'আপনার প্রতিষ্ঠান/ কর্মস্থল নাম লিখুন',
          "select_category": "ক্যাটাগরি নির্বাচন",
          "gender_select": "লিঙ্গ নির্বাচন করুন",
          "select_division": "বিভাগ নির্বাচন করুন",
          "select_district": "জেলা নির্বাচন করুন",
          "select_upazila": "উপজেলা নির্বাচন করুন",
          "select_school": "স্কুলের নাম নির্বাচন করুন",
          "facebook": 'ফেসবুক',
          "facebook_profile_link": 'ফেসবুক প্রোফাইলের লিংক',
          "linkedin": "লিংকডইন",
          "linkedin_profile_link": 'লিংকডইন প্রোফাইলের লিংক',
          "dlc_interest": "আপনি কি DLC-তে নিয়মিত কোর্স করতে/নিতে আগ্রহী?",
          "dlc_internet": "ইন্টারনেটে আপনি কি কোনো নেতিবাচক অভিজ্ঞতার স্বীকার হয়েছেন?",
          "update": 'আপডেট করুন',

          "registration_title": "ব্যবহারকারী নিবন্ধন ফর্ম",
          "enter_your_full_name": "আপনার পুরো নাম লিখুন",
          "email_not_valid": 'ইমেইল সঠিক নয়',
          "enter_your_phone_number": "আপনার মোবাইল নম্বর লিখুন",
          "select_gender": "আপনার লিঙ্গ নির্বাচন",
          "enter_password": "পাসওয়ার্ড টাইপ করুন",
          "password_need": 'পাসওয়ার্ড আবশ্যক।',
          "reenter_password": "পুনরায় পাসওয়ার্ড টাইপ করুন",
          "confirm_password_not_match": 'কন্ফার্ম পাসওয়ার্ড মেলেনি',

          "profile_update": "প্রোফাইল আপডেট",
          "write_your_phone_number": "আপনার মোবাইল নম্বর লিখুন",
          "school_name": "স্কুলের নাম",
          "campaigns": "ক্যাম্পেইন",
          "are_you_sure": "আপনি কি নিশ্চিত?",
          "cancel": "বাতিল",
          "delete_account": "অ্যাকাউন্ট মুছে ফেলুন",
          "delete": "মুছে ফেলা",

          "total_school": "স্কুল সংযুক্ত আছে",
          "total_student": "ছাত্রছাত্রী সংযুক্ত আছে",
          "total_parents": "অভিভাবক সংযুক্ত আছে",
          "total_youths": "যুবক সংযুক্ত আছে",
          "total_certificate": "ইন্টারনেট পাস",
          "video_library": "ভিডিও লাইব্রেরি"
        },
      };
}
